# Generated by Django 4.2.6 on 2023-11-28 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='openingHours',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='venueType',
            field=models.CharField(default='Bar', max_length=100),
            preserve_default=False,
        ),
    ]
