# Generated by Django 4.2.6 on 2023-12-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venue_openinghours_venue_venuetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
